apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-fwwuhcrr
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-fwwuhcrr:7dc76ca87fb5c364a93db349e967a67fca0cf544@sha256:17ac821ff83192a4fe0fe73101bbb96b8f97dc3bd09491fe8f38828c0dcae2a3
          name: container-image
